config/routes.rb
Rails.application.routes.draw do
  resources :users, except:[:index] do
    post :new_confirm, on: :collection
    patch :edit_confirm, on: :member
    get :leaving, on: :member
    resources :likes, only:[:index]
  end

  resources :sessions, only:[:new, :create, :destroy]

  resources :posts do
    post :new_confirm, on: :collection
    patch :edit_confirm, on: :member
    resources :comments, only:[:index, :create, :destroy]
    resources :likes, only: [:create, :destroy]
  end


  root :to => 'sessions#new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :id,
      uniqueness: true
  validates :user_id,
      presence: true
  validates :post_id,
      presence: true
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @likes = Like.where(user_id: @user.id).reverse_order
  end

  def create
    @like = current_user.likes.create(post_id: params[:post_id])
    @like.save
    # redirect_to post_path(@like.post_id)
    @posts = Post.all
    @post = Post.find(params[:post_id])
    @likes = Like.where(post_id: params[:post_id])
  end

  def destroy
    @like = current_user.likes.find_by(post_id: params[:post_id])
    @like.destroy
    # redirect_to posts_path
    @posts = Post.all
    @post = Post.find(params[:post_id])
    @likes = Like.where(post_id: params[:post_id])
  end
end

app/views/likes/_likes.html.erb
  <% if Like.find_by(post_id: post.id, user_id: current_user.id) %>
    <%= link_to post_like_path(post_id: post.id, id: current_user.likes.find_by(post_id: post.id).id), method: :delete, id: "like_btn", remote: true do %>
      <span class="fa fa-heart like-btn"></span>
    <% end %>
  <% else %>
    <%= link_to post_likes_path(post_id: post.id), method: :post, id: "like_btn", remote: true do %>
      <span class="fa fa-heart like-btn-unlike"></span>
    <% end %>
  <% end %>
  <span id="like_count_<%= post.id %>"><%= "#{post.likes.count}人のお気に入り" if post.likes.count > 0 %> </span>

  <div id="like_users_<%= post.id %>" class="like-box white-shadow">
    <p>お気に入り登録したユーザー</p>
    <% post.like_users.each do |like_user| %>
      <ul>
        <li>
          <b><%= link_to like_user.name, user_path(like_user.id) %></b>
          <span class="break"></span>
          <% unless like_user.description.blank? %>
            <%= "#{like_user.description.truncate(25)}" %>
          <% end %>
        </li>
      </ul>
    <% end %>
  </div>

<style>
#like_users_<%= post.id %>{
 display: none;
 p{
  margin: 0;
 }
}

#like_count_<%= post.id %>{
  text-decoration: underline;
}
#like_count_<%= post.id %>:hover{
  cursor: pointer;
}
</style>

<script>
 $(function(){
   $('#like_count_<%= post.id %>').on('click', function(){
     $('#like_users_<%= post.id %>').slideToggle(400);
   });
 });
</script>

app/views/likes/create.js.erb
$('#likes_area_<%= @post.id %>').html("<%= j(render partial: 'likes', locals: { posts: @posts, post: @post, like: @like }) %>")

app/views/likes/destroy.js.erb
$('#likes_area_<%= @post.id %>').html("<%= j(render partial: 'likes', locals: { posts: @posts, post: @post, like: @like }) %>")

app/views/likes/index.html.erb
<article class="row">
  <div class="user">
    <h3 class="col-md-offset-2 col-md-8 col-md-offset-2 col-sm-offset-1 col-sm-10">
      お気に入り作品
    </h3>

    <%= render 'users/likes' %>
  </div>
</article>