config/routes.rb
Rails.application.routes.draw do
  resources :users, except:[:index] do
    post :new_confirm, on: :collection
    patch :edit_confirm, on: :member
    get :leaving, on: :member
    resources :likes, only:[:index]
  end

  resources :sessions, only:[:new, :create, :destroy]

  resources :posts do
    post :new_confirm, on: :collection
    patch :edit_confirm, on: :member
    resources :comments, only:[:index, :create, :destroy]
    resources :likes, only: [:create, :destroy]
  end


  root :to => 'sessions#new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
    mount_uploader :image, ImageUploader
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    has_secure_password
    has_many :posts, dependent: :destroy
    has_many :comments, dependent: :destroy
    has_many :likes, dependent: :destroy

    validates :name,
        presence: true,
        length: { maximum: 30, allow_blank: true }
    validates :email,
        presence: true, length: { maximum: 255 },
        format: { with: VALID_EMAIL_REGEX, allow_blank: true },
        uniqueness: { allow_blank: true }
    validates :password,
        presence: true,
        length: { minimum: 6 },
        allow_nil: true

    before_save :downcase_email

    private
      def downcase_email
        self.email.downcase!
      end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :edit_confirm, :update, :leaving, :destroy, :ensure_correct_user]
  before_action :authenticate_user, only: [:show, :edit, :update]
  before_action :forbid_login_user, only:[:new, :create]
  before_action :ensure_correct_user, only: [:edit, :update]

  def new
    if params[:back]
      @user = User.new(user_params)
    else
      @user = User.new
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Tanka.へようこそ！"
      redirect_to posts_path
    else
      render "new"
    end
  end

  def new_confirm
    @user = User.new(user_params)
    render  "new" if @user.invalid?
  end

  def show
    @likes = @user.likes
  end

  def edit
    if params[:back]
      @user.attributes = user_params
    end
  end

  def edit_confirm
    @user.attributes = user_params
    render "edit" if @user.invalid?
  end

  def update
    @user.attributes = user_params
    @user.image.retrieve_from_cache!(params[:cache][:image]) if params[:cache][:image].present?
    if @user = User.update(user_params)
      flash[:notice] = "プロフィールを編集しました"
      redirect_to user_path(params[:id])
    else
      render "edit"
    end
  end

  def leaving
  end

  def destroy
    @user.destroy
    session.delete(:user_id)
    flash[:notice] = "ユーザー情報を削除しました。\nご利用ありがとうございました。"
    redirect_to new_session_path
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :description, :image, :image_cache)
    end

    def set_user
      @user = User.find(params[:id])
    end

    def ensure_correct_user
      if @current_user.id != params[:id].to_i
        flash[:danger]="権限がありません"
        redirect_to posts_path
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper
  def users_new_or_edit_confirm_path
    if action_name == "new" || action_name == "new_confirm"
      new_confirm_users_path
    elsif action_name == "edit" || action_name == "edit_confirm"
      edit_confirm_user_path(@user.id)
    end
  end
end

app/views/users/_confirm.html.erb
<article class="row">
  <%= form_with(model: @user, local: true) do |f| %>
    <div class="box confirm-box col-md-offset-2 col-md-8 col-sm-offset-1 col-sm-10 col-xs-offset-1 col-xs-10">
      <ul>
        <%= f.hidden_field :name %>
        <%= f.hidden_field :email %>
        <%= f.hidden_field :password %>
        <%= f.hidden_field :password_confirmation %>
        <%= f.hidden_field :description %>
        <%= f.hidden_field :image %>
        <%= f.hidden_field :image_cache %>

        <li><b>お名前</b></li>
        <li><%= @user.name %></li>

        <li><b>Email</b></li>
        <li><%= @user.email %></li>

        <li><b>パスワード</b></li>
        <li><%= "(secret.)" %></li>

        <li><b>パスワード(確認)</b></li>
        <li><%= "(secret.)" %></li>
      <% if logged_in? %>
        <li><b>自己紹介</b></li>
        <li><%= @user.description.gsub(/\r\n|\r|\n/, "<br />").html_safe %></li>
        <li><b>プロフィールアイコン</b></li>
        <li class="profile-image"><%= image_tag @user.image.url %></li>
        <%= hidden_field_tag :"cache[image]", @user.image.cache_name %>
      <% end %>
     </ul>
    </div>
    <ul>
      <div><%= f.submit "登録する", id:"btn", class:"submit-btn col-md-offset-8 col-md-2 col-sm-offset-4 col-sm-4 col-xs-offset-1 col-xs-10" %></div>
    </ul>
  <% end %>
</article>

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true, url: users_new_or_edit_confirm_path) do |f| %>
  <%= render partial: 'shared/errors', locals:{ obj: @user }%>

    <ul>
      <li class="row">
        <%= f.label :"お名前", class:"col-md-offset-2 col-md-3 col-sm-12 col-xs-12" %>
        <%= f.text_field :name, class:"col-md-4" %>
      </li>
      <li class="row">
        <%= f.label :"Email", class:"col-md-offset-2 col-md-3 col-sm-12 col-xs-12" %>
        <%= f.email_field :email, class:"col-md-4" %>
      </li>
      <li class="row">
        <%= f.label :"パスワード", class:"password col-md-offset-2 col-md-3 col-sm-12 col-xs-12" %>
        <%= f.password_field :password, class:"password col-md-4" %>
      </li>
      <li class="row">
        <%= f.label :"パスワード(確認)", class:"col-md-offset-2 col-md-3 col-sm-12 col-xs-12" %>
        <%= f.password_field :password_confirmation, class:"password col-md-4" %>
      </li>
      <% if logged_in? %>
        <li class="row profile-desc"><%= f.label :"自己紹介", class:"col-md-offset-2 col-md-3 col-sm-12 col-xs-12" %>
          <%= f.text_area :description, class:"col-md-4" %>
        </li>
        <li class="row profile-desc"><%= f.label :"＋写真を選択", class:"col-md-offset-2 col-md-3 col-sm-12 col-xs-12" %>
          <span class="upload">
            <%= f.file_field :image, class:"col-md-4" %>
            <%= f.hidden_field :image_cache %>
          </span>
        </li>
      <% end %>

      <li class="row bottom-margin">
        <%= f.submit "確認する", id: "btn", class:"col-md-offset-5 col-md-2" %>
      </li>
    </ul>

  <% end %>
</section>

app/views/users/_likes.html.erb
<% if @likes.present? %>
  <% @likes.each do |like| %>
    <% post = Post.find_by(id: like.post_id) %>
      <div class="box user-post col-md-offset-2 col-md-8 col-sm-offset-1 col-sm-10 col-xs-offset-1 col-xs-10">
        <div class="post-content">
          <div class="index-post-image"><%= link_to image_tag(post.image), post_path(post) if post.image.present? %></div>
          <h2><%= link_to post.content, post_path(post.id) %></h2>
        </div>

        <div class="post-info">
          <ul>
            <li><%= render partial: 'shared/user_info', locals: { user: post.user } %></li>
            <li><%= simple_time(post.created_at) %></li>
            <li>
              <div id="likes_area_<%= post.id %>" class="likes-area">
                <%= render partial: 'likes/likes', locals:{ post: post } %>
              </div>
            </li>
          </ul>
        </div>
      </div>
  <% end %>
<% else %>
  <p class="yet path col-md-12 col-sm-12 col-xs-12">
    まだお気に入りはありません。
  </p>
<% end %>

app/views/users/_posts.html.erb
<% if @user.posts.present? %>
  <% @user.posts.reverse_order.each do |post| %>
    <div class="box user-post col-md-offset-2 col-md-8 col-sm-offset-1 col-sm-10 col-xs-offset-1 col-xs-10">
      <div class="post-content">
        <div class="index-post-image"><%= link_to image_tag(post.image), post_path(post) if post.image.present? %></div>
        <h2><%= link_to post.content, post_path(post.id) %></h2>
      </div>
      <div class="post-info">
        <ul>
          <li><%= simple_time(post.created_at) %></li>
          <li>
            <div id="likes_area_<%= post.id %>" class="likes-area">
              <%= render partial: 'likes/likes', locals:{ post: post } %>
            </div>
          </li>
        </ul>
      </div>
    </div>
  <% end %>
<% else %>
    <p class="yet path col-md-12 col-sm-12 col-xs-12">
      まだ投稿はありません。
    </p>
<% end %>

app/views/users/_profile.html.erb
<div class="box profile row col-md-offset-2 col-md-8 col-sm-offset-1 col-sm-10 col-xs-offset-1 col-xs-10">
    <div class="profile-image col-md-4 col-sm-4">
      <% if @user.image.present? %>
        <%= image_tag @user.image  %>
      <% else %>
        <%= image_tag "default.png"  %>
      <% end %>
    </div>
    <p><b>自己紹介</b></p>
    <% if @user.description.present? %>
      <p><%= @user.description.gsub(/\r\n|\r|\n/, "<br />").html_safe %></p>
    <% else %>
      <p>まだ自己紹介はありません。</p>
    <% end %>
  <p class="path">
    <% if @user.id == @current_user.id %>
      <%= link_to "→編集", edit_user_path(@user.id) %>
    <% end %>
  </p>
</div>

app/views/users/edit.html.erb
<article class="row background">
  <div class="user">
    <h3 class="col-md-offset-1 col-md-10 col-md-offset-1 col-sm-offset-1 col-sm-10">
      プロフィールを編集
    </h3>
    <p class="back col-md-offset-1 col-md-10 col-md-offset-1 col-sm-offset-1 col-sm-10">
      <%= link_to "←もどる", user_path(@user) %>
    </p>
    <div class="profile-item col-md-offset-1 col-md-10 col-sm-offset-1 col-sm-10">
      <%= render "form" %>
      <div class="danger-sign col-md-offset-2 col-md-8 col-sm-offset-1 col-sm-10">
        DANGER!!<br>
        <%= link_to "ユーザー情報を削除する", leaving_user_path(@user) %>
      </div>
    </div>



  </div>

</article>

app/views/users/edit_confirm.html.erb
<div class="user">
  <h3 class="col-md-offset-1 col-md-10 col-md-offset-1 col-sm-offset-1 col-sm-10">
    以下の内容で登録しても良いですか？
  </h3>

  <%= render "confirm" %>

  <%= form_with(model: @user, local: true, url: edit_user_path(@current_user.id), method: :get) do |f| %>
    <%= f.hidden_field :name %>
    <%= f.hidden_field :email %>
    <%= f.hidden_field :password %>
    <%= f.hidden_field :password_digest %>
    <%= f.hidden_field :description %>
    <%= f.hidden_field :image %>
    <%= f.hidden_field :image_cache %>
    <div class="row bottom-margin">
      <%= f.submit :"もどる", name: "back", id: "btn", class:"submit-btn col-md-offset-8 col-md-2 col-sm-offset-4 col-sm-4 col-xs-offset-1 col-xs-10" %>
    </div>
  <% end %>
</div>

app/views/users/leaving.html.erb
<article class="row">

  <div class="user">
    <h3 class="col-md-offset-2 col-md-8 col-md-offset-2 col-sm-offset-1 col-sm-10">
      ユーザー情報を削除すると<br>
      投稿した作品、<span class="break"></span>コメント、お気に入りが<span class="break"></span>
      全て抹消されます。<br>
      本当によろしいですか？
    </h3>
    <h3 class="col-md-offset-4 col-md-8 col-md-offset-2 col-sm-offset-1 col-sm-10">
      <%= @user.name %>
    </h3>
    <div id="user-menu-profile"><%= render 'profile' %></div>
  </div>
  <div class="col-md-offset-2 col-md-8 col-sm-offset-1 col-sm-10 col-xs-offset-1 col-xs-10">
    <div class="back-box">
      <%= link_to "もどる", user_path(@user) %>
    </div>
    <div class="danger-sign">
      DANGER!!<br>
      <%= link_to "ユーザー情報を削除する", user_path(@user), method: :delete, data: {confirm: "本当によろしいですか？"} %>
    </div>
  </div>
</article>

app/views/users/new.html.erb
<div class="top-page">
  <% unless @user.errors.any? %>
    <div class="top-disc">
      <p>
        Tanka is a classical Japanese poetry form<br> 
        consisted of five units usually with the following pattern of on 5-7-5-7-7.
      </p>
      <h1>５・７・５・７・７の文学の世界へ。</h1>
      
      <p>
        短歌は、日本の誇る伝統的な短詩です。<br>
        古くから日本人は、日々の出来事、喜びや悲しみ、風景や自然を、<br>
        ５・７・５・７・７のわずか３１文字に託してきました。
      </p>
      <h4 class="bottom-margin">Tanka.は、あなたの短歌作品を自由に投稿できる新しいSNSです。</h4>
    </div>
    <h3 class="center bottom-margin">Tanka.をはじめる</h3>
  <% end %>
  
    
  <ul>
    <li><%= render "form" %></li>
  </ul>
</div>

app/views/users/new_confirm.html.erb
<div class="user">
  <h3 class="col-md-offset-1 col-md-10 col-md-offset-1 col-sm-offset-1 col-sm-10">
    以下の内容で登録しても良いですか？
  </h3>

  <%= render "confirm" %>

  <%= form_with(model: @user, local: true, url: new_user_path, method: :get) do |f| %>
    <%= f.hidden_field :name %>
    <%= f.hidden_field :email %>
    <%= f.hidden_field :password %>
    <%= f.hidden_field :password_digest %>
    <div class="row bottom-margin">
      <%= f.submit :"もどる", name: "back", id: "btn", class:"submit-btn col-md-offset-8 col-md-2 col-sm-offset-4 col-sm-4 col-xs-offset-1 col-xs-10" %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<article class="row">
  <div class="user">
    <h3 class="col-md-offset-2 col-md-8 col-md-offset-2 col-sm-offset-1 col-sm-10">
      <%= @user.name %>
    </h3>

    <ul class="col-md-offset-2 col-md-10 col-sm-offset-2 col-sm-10 col-xs-offset-2 col-xs-10">
      <li class="path user-menu" id="user-menu-posts-btn">
        → 投稿作品
      </li>
      <li class="path user-menu" id="user-menu-likes-btn">
        → お気に入り
      </li>
      <li class="path user-menu" id="user-menu-profile-btn">
        → プロフィールにもどる
      </li>
    </ul>

    <h3 id="user-title-posts" class="col-md-offset-2 col-md-8 col-md-offset-2 col-sm-offset-1 col-sm-10">
      投稿作品
    </h3>
    <h3 id="user-title-likes" class="col-md-offset-2 col-md-8 col-md-offset-2 col-sm-offset-1 col-sm-10">
      お気に入り
    </h3>

    <div id="user-menu-profile"><%= render 'profile' %></div>
    <div id="user-menu-posts"><%= render 'posts' %></div>

    <div id="user-menu-likes"><%= render 'likes' %></div>

  </div>
</article>

<script>
 $(function(){
   $('#user-menu-posts-btn').on('click', function(){
    $('#user-menu-posts-btn, #user-title-profile, #user-title-likes').hide();
    $('#user-menu-profile, #user-menu-likes').hide();
    $('#user-menu-profile-btn, #user-menu-likes-btn, #user-title-posts').show();
    $('#user-menu-posts').show();
   });
   $('#user-menu-likes-btn').on('click', function(){
    $('#user-menu-likes-btn, #user-title-profile, #user-title-posts').hide();
    $('#user-menu-profile, #user-menu-posts').hide();
    $('#user-menu-profile-btn, #user-menu-posts-btn, #user-title-likes').show();
    $('#user-menu-likes').show();
   });
   $('#user-menu-profile-btn').on('click', function(){
    $('#user-menu-profile-btn, #user-title-posts, #user-title-likes').hide();
    $('#user-menu-posts, #user-menu-likes').hide();
    $('#user-menu-likes-btn, #user-menu-posts-btn, #user-title-profile').show();
    $('#user-menu-profile').show();
   });
 });
</script>