config/routes.rb
Rails.application.routes.draw do
  resources :users, except:[:index] do
    post :new_confirm, on: :collection
    patch :edit_confirm, on: :member
    get :leaving, on: :member
    resources :likes, only:[:index]
  end

  resources :sessions, only:[:new, :create, :destroy]

  resources :posts do
    post :new_confirm, on: :collection
    patch :edit_confirm, on: :member
    resources :comments, only:[:index, :create, :destroy]
    resources :likes, only: [:create, :destroy]
  end


  root :to => 'sessions#new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.erb
<header>
  <% if @current_user %>
    <h1><%= link_to "Tanka.", posts_path %></h1>
  <% else %>
    <h1><%= link_to "Tanka.", root_path %></h1>
  <% end %>

  <nav>
    <% if logged_in? %>
      <p>
        <%= link_to_unless_current "作品一覧", posts_path %> |
        <%= link_to_unless_current "新規投稿", new_post_path %> |
        <%= link_to_unless_current "お気に入り", user_likes_path(current_user.id) %> |
        <span class="break"></span>
        <%= link_to_unless_current "プロフィール", user_path(current_user.id) %> |
        <%= link_to "ログアウト", session_path(current_user.id), method: :delete %>
      </p>
    <% else %>
      <p>
        <%= link_to_unless_current "ログイン", new_session_path %> |
        <%= link_to_unless_current "新規登録", new_user_path %>
      </p>
    <% end %>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tanka.</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--font-awesomeの読み込み-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>

  <body>
    <%= render 'layouts/header' %>
      <div class="container">
        <% flash.each do |key, value| %>
          <div class="flash col-md-offset-2 col-md-8 col-sm-offset-1 col-sm-10"><%= content_tag(:div, value, class: "#{key}") %></div>
        <% end %>

        <%= content_for?(:content) ? yield(:content) : yield %>
      </div>
    <p id="pageTop"><a href="#"><i class="fa fa-arrow-up" aria-hidden="true"></i></a></p>
  </body>
</html>


<script>
$(function(){
var topBtn=$('#pageTop');
topBtn.hide();

$(window).scroll(function(){
  if($(this).scrollTop()>80){
    topBtn.fadeIn();
  }else{
    topBtn.fadeOut();
  }
});

topBtn.click(function(){
  $('body,html').animate({
  scrollTop: 0},500);
  return false;
  });
});
</script>

app/views/layouts/top_page.html.erb
<% content_for :content do %>
  <article class="row">
    <div class="background">
      <div class="top-disc">
        <p class="hide-p-320">
          Tanka is a classical Japanese poetry form<br>
          consisted of five units with the following pattern of on 5-7-5-7-7.
        </p>
        <h1>わずか31文字の文学の世界へ。</h1>
        <p class="hide-p-425">
          短歌は、日本の誇る伝統的な短詩です。<br>
          古くから日本人は、日々の出来事、喜びや悲しみ、風景や自然を、<br>
          ５・７・５・７・７のリズムに託してきました。
        </p>
        <h4 class="bottom-margin">Tanka.は、あなたの短歌作品を<span class="break"></span>自由に投稿できる新しいSNSです。</h4>
        <%= yield %>
      </div>
    </div>
  </article>
<% end %>
<%= render template: 'layouts/application' %>